Parallelize CircleCI
singer-io/tap-facebook pull request #163
Opened 2021-09-16 14:49 UTC by luandy64

# Description of change
This PR breaks the one `build` job into several job that we tell Circle to run in parallel.

One change to the integration tests: we use Circle's CLI to split the tests into batches so that each batch can get picked up by an executor. The approach right now is very naive and theoretically all of the long running tests can end up in one batch. Circle has a way around this by storing timing data about the jobs, but that is not implemented here.

Because of this splitting of tests, I wanted the logs to be clear about which test is running. So here's the added logging
![Step_-_run_integration_tests__1227__-_singer-io_tap-facebook](https://user-images.githubusercontent.com/19473996/133633604-d9b6a176-1299-44c0-b84b-179a471c24fe.png)

I opted to drop the `add_ssh_keys` step. I noticed in other test runs, this step doesn't do anything.
![build__1221__-_singer-io_tap-facebook](https://user-images.githubusercontent.com/19473996/133631802-fbf05919-9c04-4c23-89c4-00f4ef03fd96.png)
Removing this does not affect our ability to run a container with SSH in Circle.

# Manual QA steps
 - Checked SSH access is not affected by removing `add_ssh_keys`
 
# Risks
 - Low
 
# Rollback steps
 - revert this branch

2021-09-16 20:07 UTC, kspeer825 requested changes
This is awesome.

2021-09-16 20:07 UTC, kspeer825 commented on .circleci/config.yml
>        - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
Can this get pushed to the most recent `stitch-tap-tester` rather than `tap-tester-v4`

2021-09-20 17:59 UTC, luandy64 commented on tests/test_facebook_tests_run.py
> +    'tap-facebook-square/tests/',
This seems like a bug

2021-09-23 19:08 UTC, kspeer825 approved these changes
This is sweet. A dev should probably review this though.

2021-09-23 20:27 UTC, cosimon approved these changes

2021-09-24 14:57 UTC, merged